configs:
  telegraf_config:
    file: ./telegraf.conf
  mosquitto_config:
    file: ./mosquitto.conf

networks:
  internal:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "false"
      com.docker.network.bridge.host_binding_ipv4: "0.0.0.0"
  internet_access:

services: 
  telegraf:    
    image: telegraf:1.34
    networks:
      internet_access:
      internal:
        gw_priority: -1
    env_file: .env
    command: /bin/sh -c 'rm /var/log/telegraf/*; rm -r /var/log/telegraf/buffer; telegraf'
    configs:
      - source: telegraf_config
        target: /etc/telegraf/telegraf.conf
    volumes:
      - telegraf_logs:/var/log/telegraf

  mqtt:
    image: eclipse-mosquitto:latest
    networks:
      - internal
    configs:
      - source: mosquitto_config
        target: /mosquitto/config/mosquitto.conf

  tester:
    networks:
      internet_access:
      internal:
        gw_priority: -1
    build: ./
    env_file: .env
    volumes:
      - telegraf_logs:/var/log/telegraf
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
   telegraf_logs: 
